Moonsong-Labs/storage-hub

pallets/file-system/src/benchmarking.rs, pallets/file-system/src/lib.rs, pallets/file-system/src/tests.rs, pallets/file-system/src/utils.rs
Refactored `on_idle` to manage clearing storage requests from old blocks up to the current block if any based on `NextStartingBlockToCleanUp`. 
Iterating over every old block number until we reach the current block while clearing all expired storage requests from `StorageRequestExpirations`. 
This iteration maintains the `total_used_weight` to avoid exceeding the `remaining_weight` for the current block.
=> feat: pallet-file-system clear storage requests up to current block `on_idle`

Cargo.lock, pallets/storage-proofs/Cargo.toml, pallets/storage-proofs/src/lib.rs, pallets/storage-proofs/src/types.rs, pallets/storage-proofs/src/utils.rs, runtime/Cargo.toml
This PR:
- Makes the old `storage-proofs` pallet be abstracted over the fact that the providers are storage providers (now they're just "Providers").
- Defines a trait to be implemented by another pallet, that would give it information of the Providers. This trait should be implemented by the Storage Providers pallet.
=> refactor: ♻️ `storage-proofs` -> `proofs-dealer-trie`

pallets/file-system/src/mock.rs, pallets/proofs-dealer/src/mock.rs, pallets/providers/src/lib.rs, pallets/providers/src/mock.rs, pallets/providers/src/tests.rs, pallets/providers/src/types.rs, pallets/providers/src/utils.rs, runtime/src/configs/mod.rs
In this PR we:
- Organize the errors of the `Providers` pallet to keep them tidy
- Implement the `change_capacity` extrinsic to allow SPs to change their "contracted" capacity
- Refactor the Main Storage Provider and Backup Storage Provider structures to add a timestamp of the last block where the capacity was changed, to use for the timelock of `change_capacity`
- Add errors for the `change_capacity` extrinsic
- Improved documentation for the functions of the `Providers` pallet
- Add success and failure tests for new functionality
=> feat: ✨ implement `change_capacity` extrinsic on the `Providers` pallet

node/src/cli.rs, node/src/command.rs, node/src/rpc.rs, node/src/service.rs
This PR adds the ability to specify the type of sealing in `--dev` mode:
Options:
- `--sealing manual`: manually execute RPC call to create blocks
- `--sealing instant`: blocks are instantly created (not finalized, but we could add an option later)
- `--sealing 6000`: blocks are created on a millisecond interval (in this case 6 seconds)
=> feat: ✨ Dev mode sealing - [Instant, Manual, Interval]

.github/workflows/rust-tests.yml
Added new CI for our rust tests.
- Uses `nextest` because it's just better than `cargo test`
- Uses archive and partitions so that it runs across multiple runners
- Is very slow, but that's unsurprising considering the specs of GHA basic tier runners
=> ci: :sparkles: Add rust-test ci

Cargo.lock, Cargo.toml, client/forest-manager/src/prove.rs, support/primitives/src/lib.rs, support/primitives/src/tests.rs
There was a bug with the double ended iteration implemented in `trie-db` which broke the behaviour expected for `next_back()` to yield either `None` or the previous leaf node after `seek(challenge)`. 
The fix was merged in https://github.com/paritytech/trie/pull/215 with a minor version upgrade from  `trie-db@0.29.0` to `trie-db@0.29.1`. Since it is a minor version, we can apply it to our dependencies without requiring `sp-trie` to upgrade it's sub dependency on `trie-db`.
Changes:
- Upgrades `trie-db` to `0.29.1`
- Removed ignored unit tests that were failing before due to bug in previous `trie-db` version
- Remove false check for `prev_leaf` which can be `None` now based on fixed double ended trie iteration behaviour
- Fix broken test to match `prev_leaf` to be `None` instead of being …
=> feat: ✨ Upgrade trie-db 0.29.1

client/common/src/types.rs, client/file-manager/src/in_memory.rs, client/file-manager/src/traits.rs
This PR extracts `FileDataTrie` from `FileStorage`, allowing the use of the file data trie and building of the file `Fingerprint` without the use of `FileStorage`. `FileStorage` now also accepts adding complete files.
=> Refactor: Extract FileDataTrie from FileStorage

pallets/payment-streams/README.md, pallets/payment-streams/src/lib.rs, pallets/payment-streams/src/mock.rs, pallets/payment-streams/src/tests.rs, pallets/payment-streams/src/types.rs, pallets/payment-streams/src/utils.rs, pallets/providers/src/lib.rs, runtime/src/configs/mod.rs, support/traits/src/lib.rs
Huuuuge PR that completely revamps the `payment-streams` pallet logic to be generalized over a generic Provider instead of being tightly tied with specifically ___storage___ providers.
This PR:
- Makes the `payment-streams` pallet able to manage two different types of payment streams: fixed-rate (useful in our case for MSPs) and dynamic-rate (useful in our case for BSPs) payment streams.
- Fixed-rate payment streams are the ones where there's a type of contract between the Provider and the User, where the Provider agrees to Provider X amount of units of something to the User for a fixed rate of tokens per unit per block. This payment stream CAN be updated (to update the rate, for example if the contract conditions change), it is fixed in the sense of a steady rate that only changes by …
=> feat: :sparkles: generalize `payment-streams` pallet over a Provider

Cargo.lock, pallets/bucket-nfts/Cargo.toml, pallets/bucket-nfts/src/mock.rs, pallets/file-system/src/mock.rs, pallets/payment-streams/Cargo.toml, pallets/payment-streams/src/mock.rs, pallets/proofs-dealer/src/mock.rs, pallets/proofs-dealer/src/tests.rs, pallets/providers/src/lib.rs, pallets/providers/src/mock.rs, pallets/providers/src/tests.rs, pallets/providers/src/types.rs, pallets/providers/src/utils.rs, runtime/src/configs/mod.rs
This PR refactors the previous logic used to get the default BSP and Bucket root. It still uses the root of an empty Merkle trie, but in a more generic and configurable way using a configuration constant and a Get implementation
=> refactor: :recycle: refactor implementation for default merkle trie root

pallets/providers/src/lib.rs, pallets/providers/src/tests.rs, pallets/providers/src/utils.rs
This PR:
- Adds new `MainStorageProviderIdsToBuckets`
- Adds and removes bucket id from list in storage in `MutateProvidersInterface`'s `add_bucket` and `remove_root_bucket` functions
- Adds test for both functions to test storage updates
=> feat: MSP to Bucket storage

client/common/src/types.rs, client/file-transfer-service/src/events.rs, client/file-transfer-service/src/handler.rs
This PR adds a new mapping to the FileTransferService so upper layer tasks can respond back to download requests.
=> feat: create internal `RequestId` for FileTransferService

pallets/file-system/src/tests.rs, pallets/proofs-dealer/src/lib.rs, pallets/proofs-dealer/src/tests.rs, pallets/proofs-dealer/src/utils.rs
This PR:
- Accrues number of failed proof submissions for slashable providers.
- Adds documentation explaining the `LastTickProviderSubmittedProofFor` storage and how it is utilized as part of the challenging protocol.
=> feat: Accrue failed proof submissions

pallets/proofs-dealer/src/tests.rs, pallets/providers/src/utils.rs
This PR implements the actual funcionality of getting the stake of a Provider from the `Providers` pallet, and updates `ProofsDealer` tests to work with this new functionality.
=> feat: ✨  implement the `get_stake` function on the `Providers` pallet

client/rpc/src/lib.rs, node/src/rpc.rs, node/src/service.rs, node/src/services/builder.rs, node/src/services/handler.rs, node/src/tasks/bsp_download_file.rs, node/src/tasks/bsp_submit_proof.rs, node/src/tasks/bsp_upload_file.rs, node/src/tasks/mock_bsp_volunteer.rs, node/src/tasks/mock_sp_react_to_event.rs, node/src/tasks/mod.rs, node/src/tasks/slash_provider.rs, node/src/tasks/user_sends_file.rs, primitives/file-metadata/src/lib.rs
This PR removes generic `T` and `T: TrieLayout` and `HasherOutT<T>` trait bounds from `StorageHubHandler` and tasks by making it concrete. This makes working with storage and the client side easier by removing the need for awkward conversion between `HasherOutT<T>` and `H256`.
=> Refactor TrieLayout trait bound in StorageHubHandler and tasks

pallets/randomness/src/lib.rs, pallets/randomness/src/mock.rs, runtime/src/configs/mod.rs, xcm-simulator/src/storagehub/configs/mod.rs
This PR solves issue [#13](https://github.com/Moonsong-Labs/internal-storage-hub-design-audit/issues/13) of the audit, by not allowing a collator to ignore adding the randomness from the relay chain into StorageHub.
=> fix: :adhesive_bandage: panic when building block if the collator doesn't include randomness

client/file-transfer-service/src/handler.rs, node/src/tasks/bsp_upload_file.rs
This fixes `FileTransferService`'s `RegisterNewFile` command and also adds back the unregister once a file is complete.
=> fix FileTransferService register

pnpm-lock.yaml, test/package.json, test/suites/integration/bsp/onboard.test.ts, test/suites/integration/bsp/slash-provider.test.ts, test/util/asserts.ts, test/util/bspNet/helpers.ts, tsconfig.json
- New helper: `assertExtrinsicPresent()`
```ts
async function assertExtrinsicPresent(
api: BspNetApi,
options: {
blockHeight?: string;
blockHash?: string;
skipSuccessCheck?: boolean;
checkTxPool?: boolean;
module: string;
method: string;
ignoreParamCheck?: boolean;
}
): Promise<
{
module: string;
method: string;
extIndex: number;
}[]
> 
```
- Will check the last block for extrinsic of `module.method`, throws or returns filtered list
- Option to check against pending txPool instead of last block
- Option to check of a particular block instead
- Will verify whether the input module.method exists in the api blob (e.g. check for typos). Has option to disable
- Will verify that it has associated extrinsicSuccess Event, with option to disable.
=> test: 🧪 Add BSP testshelper

.github/workflows/lint.yml, .github/workflows/parachain.yml
This PR introduces two new CI tasks that aim to keep `main` branch as pristine as possible.
- `typegen_check` - Downloads the node, builds a docker image, runs typegen against it and then does a git diff to see if any new interfaces have been generated. If so, will error.
- Purpose of this is to flag that this PR has changed the types interfaces, and so we should update the bindings to make sure the tests are doing the right thing.
- `typecheck-ts` - Runs `tsc` (the official Typescript Compiler) against the test project to show any type errors. This is especially useful during refactors or changes to the bindings which may not break a test, but still mismatch between inputs which given inconsistencies.
> [!IMPORTANT]  
> This PR only makes sense once …
=> feat: :sparkles:  New CIs to keep `main` pristine 

Cargo.lock, client/forest-manager/Cargo.toml, client/forest-manager/src/prove.rs, client/forest-manager/src/rocksdb.rs, test/package.json, test/suites/integration/bsp/submit-proofs.test.ts
This PR:
- Adds, for each leaf of a proof, the previous and next one to make sure the generated proof is complete enough to be able to use `apply_delta` for file removals.
- Adds the test to check that this logic is working.
- Completes the proof submission integration test except for actually checking if a file is in storage (which could be done after #191 is merged)
=> fix: 🩹 add extra required leafs in proof generation to be able to use `apply_delta`

pallets/file-system/src/tests.rs, pallets/file-system/src/utils.rs
=> fix: 🐛 correctly update Bucket root when MSP uses `stop_storing_for_insolvent_user`

pallets/file-system/src/mock.rs, pallets/proofs-dealer/src/lib.rs, pallets/providers/src/mock.rs, pallets/providers/src/utils.rs, primitives/traits/src/lib.rs, xcm-simulator/src/storagehub/configs/mod.rs
This PR:
1. Implements `integrity_test` hook in the Proofs Dealer pallet.
1. Checks that `CheckpointChallengePeriod` is greater or equal to the longest period a Provider can have.
2. Checks that `BlockFullnessPeriod` is smaller or equal than `ChallengeTicksTolerance`.
2. Makes the corresponding changes in every mocked runtime to abide by this test.
3. Adds `get_min_stake` function to `ReadChallengeableProvidersInterface`.
This ensures that we never build a runtime where those constraints are not met, given the constants that we set. You can test it by setting the `CheckpointChallengePeriod` in `runtime/src/configs/mod.rs` to something sufficiently small, and run `cargo test`.
=> test: ✅ Add integrity tests to Proofs Dealer pallet

.github/workflows/api-augment-publish.yml
While it seems like the API augment is being published with `pnpm` it is not. Workflow is showing a warning on the unrecognized param `command: pnpm`:
```
publish-api-augment
Unexpected input(s) 'command', valid inputs are ['token', 'registry', 'package', 'tag', 'access', 'provenance', 'strategy', 'ignore-scripts', 'dry-run']
```
This results in a published package with `pnpm`-like syntax which breaks for people installing with `npm`. Notice the `workspace:*`:
```
"dependencies": {
"@polkadot/api": "12.4.2",
"@polkadot/api-base": "12.4.2",
"@polkadot/rpc-core": "12.4.2",
"@polkadot/typegen": "12.4.2",
"@polkadot/types": "12.4.2",
"@polkadot/types-codec": "12.4.2",
"@storagehub/types-bundle": "workspace:*",
"tsx": "4.19.0",
"typescript": "5.5.4"
}
```
Threw some other changes to the …
=> CI/fix: :package: publish api-augment w/ pnpm & add dry-run

test/suites/integration/bsp/storage-capacity.test.ts, test/util/bspNet/block.ts, test/util/bspNet/testrunner.ts
Before it was being executed at the beginning of the `describeBspNet` which caused unexpected errors when a test suite was executed with `only: true` and `keepAlive: true`. Now it is executed in the `before` block of each test suite meaning two things:
1. Test suites without `only: true` are filtered out and don't execute `verifyContainerFreshness` when running `pnpm test:bspnet:only`.
2. `verifyContainerFreshness` is run on every test suite, including same test suites but with different network configs (like memory DB and Rocks DB).
=> fix: 🩹 Execute `verifyContainerFreshness` in `before` block of each test suite

test/suites/integration/bsp/submit-proofs.test.ts
Just adds a new test which verifies that proof exts are re-submitted after a reorg.
=> test: :test_tube: New proof reorg test

pallets/file-system/src/utils.rs
When updating a bucket's privacy, we were previously creating and associating a collection when changing the privacy to public (if a collection ID existed but the collection did not exist in Storage). Now, this behavior is restricted to cases where the privacy is changed to private.
Additionally, some minor comment corrections were made to clarify that the `do_create_and_associate_collection_with_bucket` function does not validate the bucket's privacy.
=> fix: 🩹 Create a collection only when updating to a private bucket

client/forest-manager/src/error.rs, client/forest-manager/src/in_memory.rs, client/forest-manager/src/rocksdb.rs, client/forest-manager/src/traits.rs, node/src/services/forest_storage.rs
This PR:
1. Adds the `snapshot` function to the `ForestStorageHandler` trait, allowing to create copies of existing Forests.
2. Implements it for the existing structs that implement `ForestStorageHandler`.
1. To be precise, this is only relevant for `ForestStorageCaching`, because `ForestStorageSingle` wouldn't be able to manage more than the one original Forest.
Testing is not included in this PR. This functionality will be tested and debug in subsequent PRs that use this new feature.
=> feat: ✨ Add `snapshot` functionality to `ForestStorageHandler`

pnpm-lock.yaml, test/package.json, test/scripts/downloadPolkadot.ts, test/scripts/modifyPlainSpec.ts, test/suites/integration/bsp/multiple-delete.test.ts, test/suites/integration/bsp/storage-delete.test.ts, test/suites/integration/bsp/submit-proofs.test.ts, test/util/asserts.ts, test/util/bspNet/block.ts, test/util/bspNet/docker.ts, test/util/bspNet/fileHelpers.ts, test/util/bspNet/helpers.ts, test/util/bspNet/node.ts, test/util/bspNet/waits.ts, test/util/helpers.ts, test/util/netLaunch/index.ts, test/util/rpc.ts, test/util/testContainers.ts, test/util/zombieHelpers.ts
This PR add an integration test that verify that duplicating several files for a BSP works correctly.
We also added a test that try to batch delete files which is not possible and fails. It was how I first approach this task.
=> test: bsp delete multiple files

runtime/src/configs/mod.rs, test/scripts/generateBenchmarkProofs.ts, test/suites/integration/bsp/bsp-thresholds.test.ts, test/suites/integration/bsp/debt-collection.test.ts, test/suites/integration/bsp/multiple-delete.test.ts, test/suites/integration/bsp/reorg-proof.test.ts, test/suites/integration/bsp/single-volunteer.test.ts, test/suites/integration/bsp/storage-capacity.test.ts, test/suites/integration/bsp/submit-proofs.test.ts, test/suites/integration/msp/debt-collection.test.ts, test/suites/integration/msp/respond-multi-requests.test.ts, test/suites/integration/msp/stop-storing-bucket.test.ts, test/util/bspNet/block.ts, test/util/bspNet/test-api.ts, test/util/bspNet/waits.ts
In this PR:
1. Fix race condition in `skipTo` waiting for proofs (eliminated `sleep`s).
2. Fix race condition where there could have been multiple `PaymentStreamCharged` events in `debt-collection.test.ts`.
3. Fix race condition where MSP didn't add a file to it's local File Storage in time in `respond-multi-requests.test.ts`.
4. Remove redundant iterations in `waitForTxInPool`.
5. Change file from `smile.jpg` to `whatsup.jpg` in `bsp-threshold.test.ts` to make it so that `BSP_DOWN` cannot immediately volunteer.
6. Simplify logic in `bsp-threshold.test.ts` and make it deterministic which BSP should be volunteering first (that shouldn't change given that their IDs and the file keys of the files uploaded don't change ever).
7. Fix race condition in `bsp-threshold.test.ts` where BSP was not …
=> test: ✅ Fix race conditions in integration tests

test/suites/integration/bsp/storage-capacity.test.ts
This PR add a test to verify that the BSP will not take more than it can store. When increasing the capacity we can batch it to satisfy all the storage requests but it should never increase more than the max set in the configuration.
=> feat: add test to verify that at max capacity bsp take only what it can store

Cargo.lock, client/blockchain-service/src/handler.rs, test/suites/integration/bsp/onboard.test.ts, test/suites/integration/bsp/storage-capacity.test.ts, test/suites/integration/bsp/storage-delete.test.ts, test/suites/integration/bsp/submit-proofs.test.ts, test/util/bspNet/waits.ts
In this PR:
1. Make Blockchain Service trigger proof submission catch up every 4 blocks (configurable) to further ensure always being up to date with proofs.
2. Solve race condition in integration tests where sometimes the BSP being awaited to catch up to chain tip, would get stuck in a previous block, never syncing until it is gossiped of a new block.
3. Solve race condition in `storage-delete.test.ts` where sometimes it generate a Forest proof before having processed the latest Forest changes.
=> feat: ✨ Trigger proof submission catch up every 4 blocks

pallets/providers/src/utils.rs, test/suites/integration/bsp/challenge-cycle-2.test.ts
Added `challenge-cycle-2.test.ts` integration test in order to test the functionality when a BSP changes their capacity (deposit/stake), their current next challenge tick has not changed only after they have reached it. We then check that the next challenge tick is expected to be calculated based on the new challenge deadline.
=> tests: Add integration tests for challenge deadlines changing based on capacity change

pallets/payment-streams/src/benchmarking.rs, pallets/payment-streams/src/lib.rs, pallets/payment-streams/src/utils.rs, pallets/proofs-dealer/src/benchmarking.rs, pallets/providers/src/benchmarking.rs, pallets/providers/src/lib.rs, pallets/providers/src/tests.rs, pallets/providers/src/utils.rs, pallets/randomness/src/benchmarking.rs, pallets/randomness/src/tests.rs
This PR removes the now not-needed generics when handling events from each pallet.
=> style: :art: remove unneeded generics in pallet events

pallets/file-system/src/utils.rs
Moved the payment stream create and update block in `bsp_confirm_storing` to skip file keys if those operations have failed.
Moving these operations at the top avoids any possibility for any storage elements from being updated when they shouldn't if we skipped the file key.
See the audit issue raised for more details.
Resolves [issue #30](https://github.com/Moonsong-Labs/internal-storage-hub-design-audit/issues/30)
=> fix: Skip BSP confirm file keys that have failed to update or create a payment stream

test/suites/integration/bsp/multiple-delete.test.ts, test/suites/integration/bsp/reorg-proof.test.ts, test/suites/integration/bsp/storage-delete.test.ts, test/suites/integration/bsp/submit-proofs.test.ts
This PR fixes a few integration tests that were left with possible race conditions. The `MinWaitForStopStoring` was updated to be retrieved from pallet-parameters instead of the constants and an await for a MSP's acceptance response in `submit-proofs` was moved to where the MSP acceptance actually happens.
=> test: :white_check_mark: fix integration tests

test/suites/integration/msp/move-bucket.test.ts, test/util/bspNet/test-api.ts, test/util/bspNet/waits.ts
This PR adds a helper that can be used in integration tests to await for a storage request to be fulfilled, and uses it in the move bucket tests to avoid a racing condition where the test tries to request to move a bucket that still has a pending storage request because the BSP wasn't able to confirm storing the file in time.
=> feat: :white_check_mark: add helper to check for storage request fulfillment

client/indexer-service/src/handler.rs
In this PR, we handle `SpStopStoringInsolventUser` event and update the indexer to remove the file we are stopping to store because the user is insolvent.
see https://github.com/Moonsong-Labs/internal-storage-hub-design-audit/issues/32
=> feat: index user insolvent event

node/src/tasks/bsp_upload_file.rs, test/suites/integration/bsp/challenge-cycle-2.test.ts, test/suites/integration/bsp/storage-capacity.test.ts, test/util/bspNet/block.ts, test/util/bspNet/test-api.ts
This PR changes the `bsp_upload_file` task (more precisely, the part where the BSP tries to increase its capacity if it's not enough) to make it less likely to run into race conditions, also gives an overall makeover to the testing of that task to minimize its chances to fail when it shouldn't
=> test: :white_check_mark: fix storage capacity test and improve its clarity

client/actors-framework/src/event_bus.rs, node/src/services/handler.rs
In this PR, we handle errors coming from the event bus receiver. It also changes the way we behave in case of `Lagged` error.
There is 2 possible errors return from the receiver : 
* `Lagged` - In this scenario we print a warning message saying that messages have been skipped and we keep reading from the receiver for new messages. This error should only happened when handling events that are p2p. If a peer fill the channel older messages will be dropped and newer will be read. The limit is 2000 events so it will limit the number of tasks being spawned at once avoiding risk of DoS by a peer. 
* `Closed` - This error will happen if there is no more available sender. It shouldn't happen normally. In this case we print a warning message and leave function.
In the scenario the event bus is …
=> misc: handle receiver errors in the event bus

client/file-transfer-service/src/lib.rs
Improves the file transfer service configuration by:
1. Making request/response packet sizes dynamic based on the batch chunk size rather than fixed 1GB limits
2. Adding a 100% overhead margin to accommodate metadata in transfer requests and proof size
3. Calculating max queued requests based on memory constraints (8GB) rather than using a fixed value of 500
resolves [issue #19](https://github.com/Moonsong-Labs/internal-storage-hub-design-audit/issues/19)
=> fix: Optimize file transfer request memory and size configuration

node/src/tasks/user_sends_file.rs, test/suites/integration/user/send-file-to-provider.test.ts, test/util/bspNet/docker.ts, test/util/pjsKeyring.ts
This PR is a small refactor of the user sending file task so it improves the logs. It also add 2 integration tests that test two scenarios : 
* The provider is offline and the user cannot connect to it. It will show the proper error message and exit with an error (the previous behavior showed a success log even when the file was not send).
* The provider has 2 libp2p multiaddresses register to its name. The first one is not valid and the user can connect. The second is correct and the user should successfully send the file.
=> fix: fail when user fail to send file to MSP after several retries

test/util/bspNet/docker.ts
This PR:
- Unifies code of testing utilities `addBspContainer` and `addMspContainer`, to improve maintainability.
=> refactor: :recycle: Unify code of `addBspContainer` and `addMspContainer`

test/suites/integration/bsp/bsp-thresholds.test.ts, test/suites/integration/bsp/challenge-cycle.test.ts, test/suites/integration/bsp/storage-capacity.test.ts, test/suites/integration/bsp/storage-delete.test.ts, test/suites/integration/bsp/submit-proofs.test.ts, test/suites/integration/user/send-file-to-provider.test.ts, test/util/bspNet/docker.ts, test/util/netLaunch/index.ts
The docker helper functions don't differentiate between BSP and MSP. In this PR we rename it to a more general name as it can be used for any kind of container.
e.g. 
Changing name `stopBspContainer` to `stopContainer`
=> refactor: change name for docker utils function in integration tests

client/blockchain-service/src/commands.rs, client/blockchain-service/src/events.rs, client/blockchain-service/src/handler.rs, client/blockchain-service/src/transaction.rs, client/blockchain-service/src/types.rs, node/src/tasks/bsp_submit_proof.rs, node/src/tasks/bsp_upload_file.rs, node/src/tasks/msp_delete_file.rs, rust-toolchain.toml, test/scripts/generateFileSystemBenchmarkProofs.ts, test/scripts/generateProofsDealerBenchmarkProofs.ts, test/suites/integration/bsp/automatic-tipping.test.ts, test/suites/integration/bsp/bsp-thresholds.test.ts, test/suites/integration/bsp/debt-collection.test.ts, test/suites/integration/bsp/multiple-delete.test.ts, test/suites/integration/bsp/reorg-proof.test.ts, test/suites/integration/bsp/single-volunteer.test.ts, test/suites/integration/bsp/storage-capacity.test.ts, test/suites/integration/bsp/storage-delete.test.ts, test/suites/integration/bsp/submit-proofs.test.ts, test/util/bspNet/test-api.ts, test/util/bspNet/types.ts, test/util/bspNet/waits.ts, test/util/netLaunch/index.ts
In this PR:
1. Add functionalities to `RetrySrategy`:
1. Now `should_retry` takes `WatchTransactionError` as an argument, to provide more information for deciding to retry or not.
2. There is a `retry_only_with_timout` that sets `should_retry` to return `true` only if the extrinsic timed out.
2. `bsp_submit_proof` task only retries sending the same transaction if the extrinsic timed out. It also checks if the proof is still up to date. If it fails beyond the retries (or it is outdated) it finishes the task with an error, trusting that the BlockchainService will check for proof submissions frequently and spawn new tasks to take care of it.
3. `bsp_upload_file` task only retries confirmation extrinsic if it times out.
4. `msp_delete_file` task only retries confirmation of deletion if it …
=> fix: 🐛 Avoid retrying in same tasks

client/actors-framework/src/constants.rs, node/src/services/handler.rs
This PR:
1. Increases the size of each event queue to 10,000.
2. Increases the max number of spawned tasks per event queue to 20,000.
3. Makes `NewStorageRequest` event not-critical.
1 and 2 are for making it so that if a user manages to spam with blockchain events (like `NewStorageRequests` or `FileDeletionRequest`, the limit is higher.
3 is so that even if a user manages to spam enough with `NewStorageRequests` to reach the limit, the policy will be to just ignore and drop those spamming `NewStorageRequests`.
=> fix: 🔒 Increase events queue size and make `NewStorageRequests` non-critical

node/src/tasks/msp_charge_fees.rs, test/suites/integration/msp/move-bucket-low-capacity.test.ts, test/suites/integration/user/send-file-to-provider.test.ts, test/util/bspNet/docker.ts, test/util/netLaunch/index.ts
This PR is a replacement for https://github.com/Moonsong-Labs/storage-hub/pull/328
> In order to test proper rejection of move bucket request on low capacity, a refactor and addition of onboardMsp (similar to onboardBsp) was needed.
=> test: MSP move bucket reject on max capacity exceeded

Cargo.lock, Cargo.toml, pallets/payment-streams/src/mock.rs, pallets/proofs-dealer/src/mock.rs, pallets/provider-randomness/src/mock.rs, pallets/providers/src/lib.rs, pallets/providers/src/mock.rs, pallets/providers/src/utils.rs, primitives/file-metadata/src/lib.rs, primitives/traits/src/lib.rs
In this PR, we pin `sp-trie` to use the `stable2409` temporarly to avoid dependencies conflict. We also make `FileMetadataInterface` AccountID agnostic to be able to use `AccountId20` or `AccountId32` without compilation errors.
=> feat: use stable2409 for sp-trie; make filemetada account type agnostic;

.github/workflows/lint.yml
In this PR we remove `actions-rust-lang/setup-rust-toolchain@v1.8` and `actions-rust-lang/rustfmt@v1` as rustfmt is already installed on ubuntu runner.
=> ci: remove unnecessary action for rustfmt

client/actors-derive/src/lib.rs, client/common/src/typed_store.rs
These crates contain procedural macros and common utilities that don't require documentation tests, and their doctests were failing. Disabling them prevents CI failures and developers running `cargo test` to encounter failures.
=> Ignore failing doctests in actors-derive and common crates

test/suites/integration/backend/upload-download-file.test.ts
Hit an [error](https://github.com/Moonsong-Labs/storage-hub/actions/runs/18046378830/job/51358587248?pr=499) where the BSP confirmation transaction was not found in the transaction pool. 
This change will ensure that at least the volunteer extrinsic happened in the previous block which normally makes this flow deterministic.
=> test: :bug: Ensure BSP volunteered in upload file integration test

sdk/core/src/init.ts
Microfix as when the SDK was initializing the WASM we were getting a `deprecated` warning, since we are now expecting an object with `module_or_path` instead of directly the WASM blob bytes.
=> fix: :bug: update call to init wasm to use object as parameter for the wasm blob

sdk/msp-client/src/index.ts, sdk/msp-client/src/types.ts
FileListResponse type didn't contain children field in its type definition
=> fix: FileList response type
